import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Results from './results'

export default function Home() {
  return (
    <>
      <Head>
        <title>Youtube Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://www.youtube.com/s/desktop/451d4225/img/favicon.ico" />
      </Head>
      <Results />
    </>
  )
}
